---
ID: "64530934-5a53-4d2f-a8ee-3ea4d2cd8fab"
Parent: "8ca4450b-86cb-4494-861f-2ab829c860a5"
Template: "cfd30fc4-07fa-471e-9f85-3a1bf425c718"
Path: /sitecore/content/manufacturing/forge/Presentation/Partial Designs/Header/Data/New Global Header/New Primary Navigation Links/Products
Languages:
- Language: en
  Versions:
  - Version: 1
