---
ID: "b315a5d1-9c91-4fb4-b752-876d30dd25f6"
Parent: "4a5c5ae5-cb53-484d-948e-94d947f8e9ea"
Template: "5c547d4e-7111-4995-95b0-6b561751bf2e"
Path: "/sitecore/layout/Placeholder Settings/Project/healthcare/Products/product-detail-banner"
SharedFields:
- ID: "7256bdab-1fd2-49dd-b205-cb4873d2917c"
  Hint: Placeholder Key
  Value: "product-detail-banner"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "66e9cc62-d518-4c8d-854b-99ffdce573e0"
- ID: "e391b526-d0c5-439d-803e-17512eae6222"
  Hint: Allowed Controls
  Value: |
    {41A33C8C-997E-4A2D-BC17-A61F2397ECCD}
    {B94588E6-1BAE-4859-AD97-28EB5FF84A10}
    {E1AD95B9-854D-4ADF-8F75-2DF1B69F80CC}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251124T020813Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8f35921c-75d0-486d-b738-ab35ffacbfc0"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251124T020833Z
