---
ID: "d7b0bdf8-2b91-472e-9fef-31773576643a"
Parent: "e2282aa0-af68-4033-ac38-14b16ca6ae62"
Template: "38183f6a-c7aa-47bd-83d6-935f2383bc5d"
Path: /sitecore/content/healthcare/vitalis/Home/Products
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{9093490E-63F1-4F96-93C3-0CF47848C8CE}"
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: |
    <image mediaid="{24AD6C15-9C20-4EEF-9ECC-E25D574FF37E}" />
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "741ac506-bd8d-4e2c-9de4-72ccbe52d196"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{94BE8E37-D031-4260-BF5D-11FD277D18B7}"
              p:before="*"
              s:ds="af040957-c137-48ef-8246-f752678d751d"
              s:id="{B94588E6-1BAE-4859-AD97-28EB5FF84A10}"
              s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames=%7B36591F98-9581-4BE1-833E-1B4BDA7F71DC%7D&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=1"
              s:ph="headless-main" />
            <r
              uid="{43C31C84-CCE9-4A38-B714-5F83991C540B}"
              p:after="*[1=2]"
              s:id="{29995697-118F-4DA8-9181-7B4C298EE390}"
              s:par="CSSStyles"
              s:ph="headless-main" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251113T201800Z
    - ID: "2c6f31e6-beda-4374-9d2b-6a4fdb6d5c15"
      Hint: metadataKeywords
      Value: Vitalis products, healthcare data platform, quality measurement tools, Stars improvement solutions, HEDIS automation products, healthcare data integration
    - ID: "48005244-445f-4d3b-b5c2-c7f1b235ff60"
      Hint: metadataTitle
      Value: Vitalis Products | Quality Measurement, Data Automation, and Performance Solutions
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Products
    - ID: "5000eb1d-4834-4c41-8106-ecb127701b47"
      Hint: metadataDescription
      Value: Explore Vitalis’ suite of healthcare technology products designed to automate HEDIS reporting, improve Stars performance, unify clinical and claims data, and support digital quality measures.
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "331b17c4-4348-477a-b1ff-daf3233d005a"
    - ID: "b7e84d23-4073-4e2a-88db-dba2a4c17a81"
      Hint: ogImage
      Value: |
        <Image src="https://starter-verticals.sitecoresandbox.cloud/api/public/content/606dbb20dd294f2fbaf1cfd20028b533?v=03b511e8" dam-id="MO4czw4cTNey6N43mTFpaw" width="350" height="350" alt="V3.jpg" dam-content-type="Image" thumbnailsrc="https://starter-verticals.sitecoresandbox.cloud/api/gateway/74658/thumbnail" />
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "d70b853d-e180-45ef-a71f-f1cfedbfd7db"
      Hint: pageSummary
      Value: The Vitalis Products Overview page outlines the platform’s full product suite, including tools for HEDIS automation, Stars performance improvement, digital quality measures, chart retrieval, and healthcare data integration.
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251124T165546Z
    - ID: "f44096a8-8c39-4257-bd0f-5f5c00c6690d"
      Hint: Title
      Value: Products
