// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import {
  combineImportEntries,
  defaultImportEntries,
  ImportEntry,
} from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { useState, forwardRef, useEffect, useCallback, createContext, useContext, useRef, useMemo, useId } from 'react';
import React from 'react';
import TabsComponent from 'src/components/layout/TabsComponent/TabsComponent';
import { RichText, Link, Text, useSitecoreContext, Placeholder } from '@sitecore-content-sdk/nextjs';
import PromoCards from 'src/components/layout/PromoCard/PromoCard';
import ProductCard from 'src/components/layout/ProductCard/ProductCard';
import MediaBannerIconLists from 'src/components/layout/MediaBannerIcon/MediaBannerIcon';
import IconCardList from 'src/components/layout/IconCardList/IconCardList';
import ContentCards from 'src/components/layout/ContentCards/ContentCardsText';
import { useModal } from 'src/components/ui/Modal/ModalProvider';
import ModalComponent from 'src/components/ui/Modal/Modal';
import { Modal, Spinner, Container, Row, Accordion, Col, Nav, Navbar, NavDropdown, Offcanvas, ListGroup } from 'react-bootstrap';
import Cookies from 'js-cookie';
import dynamic from 'next/dynamic';
import Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 from 'next/link';
import { default } from 'next/image';
import Image from 'next/image';
import ImageItem from 'src/components/ui/Image/ImageItem';
import LottieAnimation from 'src/components/ui/LottieAnimation/LottieAnimation';
import { GPVideo } from 'src/components/ui/Video/GPVideo';
import { GPImage } from 'src/components/ui/Image/GPImage';
import LinkItem from 'src/components/ui/Link/Link';
import { useRouter, withRouter } from 'next/router';
import { QuoteCardCarouselWrapper } from 'src/components/layout/Testimonial/QuoteCardCarouselWrapper';
import { useI18n } from 'next-localization';
import Filters from 'src/components/layout/SearchTagResults/Filters';
import Pagination from 'src/components/layout/SearchTagResults/Pagination';
import Results from 'src/components/layout/SearchTagResults/Results';
import PlanSelectorCard from 'src/components/layout/PlanSelectorCard/PlanSelectorCardText';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/dist/ScrollTrigger';
import Slider from 'react-slick';
import Heading from 'src/components/ui/Heading/Heading';
import Ctas from 'src/components/ui/CTA/CTA';
import { debounce } from 'lodash';
import PromoHiLoCardWrapper from 'src/components/layout/HiLoCards/PromoHiLoCard';
import { Form, createDefaultFieldFactory } from '@sitecore-jss/sitecore-jss-react-forms';
import CustomFieldFactory from 'src/components/layout/HeadlessForm/CustomFieldFactory';
import { gsap as gsap_5bf2bb5f533e7546fcecfb3a2e4ca179da74b190 } from 'gsap/dist/gsap';
import { MotionPathPlugin } from 'gsap/dist/MotionPathPlugin';
import CountUp from 'react-countup';
import Head from 'next/head';
import QuickLinkList from 'src/components/common/Header/QuickLinkList';
import { useSitecoreTracking } from 'src/components/analytics/SitecoreTracking';
import useSWR from 'swr';
import ContentCardCarousel from 'src/components/Uptick/ContentCardCarousel';
import { SocialSharing } from 'src/components/Uptick/SocialSharing';
import { UptickTaxonomy } from 'src/components/Uptick/UptickTaxonomy';
import { ContentMeta } from 'src/components/Uptick/shared/ContentMeta/ContentMeta';
import { usePathname, useSearchParams } from 'next/navigation';
import EditorialPageSearch from 'src/components/Uptick/EditorialPageHero/EditorialPageSearch';
import { Card, CardContent } from 'src/components/Uptick/ui/UptickCard';
import { TaxonomyTags } from 'src/components/Uptick/TaxonomyTags/TaxonomyTags';
import ReactPlayer from 'react-player';
import { TestimonialRenderer } from 'src/components/Uptick/ArticleDetail/TestimonialRenderer';
import { TextBlock } from 'src/components/Uptick/ArticleDetail/TextBlock';
import { TitleBlock } from 'src/components/Uptick/ArticleDetail/TitleBlock';
import { TwoColumnQuoteBlock } from 'src/components/Uptick/ArticleDetail/TwoColumnQuoteBlock';
import { TestimonialBlock } from 'src/components/Uptick/ArticleDetail/TestimonialBlock';
import { HorizontalLineBlock } from 'src/components/Uptick/ArticleDetail/HorizontalLineBlock';
import { AudioPlaybackBlock } from 'src/components/Uptick/ArticleDetail/AudioPlaybackBlock';
import { ImageBlock } from 'src/components/Uptick/ArticleDetail/ImageBlock';
import { TwoColumnTextBlock } from 'src/components/Uptick/ArticleDetail/TwoColumnTextBlock';
import { InteractiveBlock } from 'src/components/Uptick/ArticleDetail/InteractiveBlock';
import { VideoBlock } from 'src/components/Uptick/ArticleDetail/VideoBlock';
import ReactHowler from 'react-howler';
import { ComponentFactory } from 'src/components/Uptick/ArticleDetail/ComponentFactory';
import SearchResultCard from 'src/components/GeneralSearch/SearchResultCard';
import SearchInput from 'src/components/GeneralSearch/SearchInput';
import SearchPaginationBar from 'src/components/GeneralSearch/SearchPaginationBar';

const importMap = [
  {
    module: 'react',
    exports: [
      { name: 'useState', value: useState },
      { name: 'forwardRef', value: forwardRef },
      { name: 'useEffect', value: useEffect },
      { name: 'useCallback', value: useCallback },
      { name: 'createContext', value: createContext },
      { name: 'useContext', value: useContext },
      { name: 'useRef', value: useRef },
      { name: 'useMemo', value: useMemo },
      { name: 'useId', value: useId },
      { name: 'default', value: React },
    ]
  },
  {
    module: 'src/components/layout/TabsComponent/TabsComponent',
    exports: [
      { name: 'default', value: TabsComponent },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'RichText', value: RichText },
      { name: 'Link', value: Link },
      { name: 'Text', value: Text },
      { name: 'useSitecoreContext', value: useSitecoreContext },
      { name: 'Placeholder', value: Placeholder },
    ]
  },
  {
    module: 'src/components/layout/PromoCard/PromoCard',
    exports: [
      { name: 'default', value: PromoCards },
    ]
  },
  {
    module: 'src/components/layout/ProductCard/ProductCard',
    exports: [
      { name: 'default', value: ProductCard },
    ]
  },
  {
    module: 'src/components/layout/MediaBannerIcon/MediaBannerIcon',
    exports: [
      { name: 'default', value: MediaBannerIconLists },
    ]
  },
  {
    module: 'src/components/layout/IconCardList/IconCardList',
    exports: [
      { name: 'default', value: IconCardList },
    ]
  },
  {
    module: 'src/components/layout/ContentCards/ContentCardsText',
    exports: [
      { name: 'default', value: ContentCards },
    ]
  },
  {
    module: 'src/components/ui/Modal/ModalProvider',
    exports: [
      { name: 'useModal', value: useModal },
    ]
  },
  {
    module: 'src/components/ui/Modal/Modal',
    exports: [
      { name: 'default', value: ModalComponent },
    ]
  },
  {
    module: 'react-bootstrap',
    exports: [
      { name: 'Modal', value: Modal },
      { name: 'Spinner', value: Spinner },
      { name: 'Container', value: Container },
      { name: 'Row', value: Row },
      { name: 'Accordion', value: Accordion },
      { name: 'Col', value: Col },
      { name: 'Nav', value: Nav },
      { name: 'Navbar', value: Navbar },
      { name: 'NavDropdown', value: NavDropdown },
      { name: 'Offcanvas', value: Offcanvas },
      { name: 'ListGroup', value: ListGroup },
    ]
  },
  {
    module: 'js-cookie',
    exports: [
      { name: 'default', value: Cookies },
    ]
  },
  {
    module: 'next/dynamic',
    exports: [
      { name: 'default', value: dynamic },
    ]
  },
  {
    module: 'next/link',
    exports: [
      { name: 'default', value: Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 },
    ]
  },
  {
    module: 'next/image',
    exports: [
      { name: 'default', value: default },
      { name: 'default', value: Image },
    ]
  },
  {
    module: 'src/components/ui/Image/ImageItem',
    exports: [
      { name: 'default', value: ImageItem },
    ]
  },
  {
    module: 'src/components/ui/LottieAnimation/LottieAnimation',
    exports: [
      { name: 'default', value: LottieAnimation },
    ]
  },
  {
    module: 'src/components/ui/Video/GPVideo',
    exports: [
      { name: 'GPVideo', value: GPVideo },
    ]
  },
  {
    module: 'src/components/ui/Image/GPImage',
    exports: [
      { name: 'GPImage', value: GPImage },
    ]
  },
  {
    module: 'src/components/ui/Link/Link',
    exports: [
      { name: 'default', value: LinkItem },
    ]
  },
  {
    module: 'next/router',
    exports: [
      { name: 'useRouter', value: useRouter },
      { name: 'withRouter', value: withRouter },
    ]
  },
  {
    module: 'src/components/layout/Testimonial/QuoteCardCarouselWrapper',
    exports: [
      { name: 'QuoteCardCarouselWrapper', value: QuoteCardCarouselWrapper },
    ]
  },
  {
    module: 'next-localization',
    exports: [
      { name: 'useI18n', value: useI18n },
    ]
  },
  {
    module: 'src/components/layout/SearchTagResults/Filters',
    exports: [
      { name: 'default', value: Filters },
    ]
  },
  {
    module: 'src/components/layout/SearchTagResults/Pagination',
    exports: [
      { name: 'default', value: Pagination },
    ]
  },
  {
    module: 'src/components/layout/SearchTagResults/Results',
    exports: [
      { name: 'default', value: Results },
    ]
  },
  {
    module: 'src/components/layout/PlanSelectorCard/PlanSelectorCardText',
    exports: [
      { name: 'default', value: PlanSelectorCard },
    ]
  },
  {
    module: 'gsap',
    exports: [
      { name: 'default', value: gsap },
    ]
  },
  {
    module: 'gsap/dist/ScrollTrigger',
    exports: [
      { name: 'ScrollTrigger', value: ScrollTrigger },
    ]
  },
  {
    module: 'react-slick',
    exports: [
      { name: 'default', value: Slider },
    ]
  },
  {
    module: 'src/components/ui/Heading/Heading',
    exports: [
      { name: 'default', value: Heading },
    ]
  },
  {
    module: 'src/components/ui/CTA/CTA',
    exports: [
      { name: 'default', value: Ctas },
    ]
  },
  {
    module: 'lodash',
    exports: [
      { name: 'debounce', value: debounce },
    ]
  },
  {
    module: 'src/components/layout/HiLoCards/PromoHiLoCard',
    exports: [
      { name: 'default', value: PromoHiLoCardWrapper },
    ]
  },
  {
    module: '@sitecore-jss/sitecore-jss-react-forms',
    exports: [
      { name: 'Form', value: Form },
      { name: 'createDefaultFieldFactory', value: createDefaultFieldFactory },
    ]
  },
  {
    module: 'src/components/layout/HeadlessForm/CustomFieldFactory',
    exports: [
      { name: 'default', value: CustomFieldFactory },
    ]
  },
  {
    module: 'gsap/dist/gsap',
    exports: [
      { name: 'gsap', value: gsap_5bf2bb5f533e7546fcecfb3a2e4ca179da74b190 },
    ]
  },
  {
    module: 'gsap/dist/MotionPathPlugin',
    exports: [
      { name: 'MotionPathPlugin', value: MotionPathPlugin },
    ]
  },
  {
    module: 'react-countup',
    exports: [
      { name: 'default', value: CountUp },
    ]
  },
  {
    module: 'next/head',
    exports: [
      { name: 'default', value: Head },
    ]
  },
  {
    module: 'src/components/common/Header/QuickLinkList',
    exports: [
      { name: 'default', value: QuickLinkList },
    ]
  },
  {
    module: 'src/components/analytics/SitecoreTracking',
    exports: [
      { name: 'useSitecoreTracking', value: useSitecoreTracking },
    ]
  },
  {
    module: 'swr',
    exports: [
      { name: 'default', value: useSWR },
    ]
  },
  {
    module: 'src/components/Uptick/ContentCardCarousel',
    exports: [
      { name: 'default', value: ContentCardCarousel },
    ]
  },
  {
    module: 'src/components/Uptick/SocialSharing',
    exports: [
      { name: 'SocialSharing', value: SocialSharing },
    ]
  },
  {
    module: 'src/components/Uptick/UptickTaxonomy',
    exports: [
      { name: 'UptickTaxonomy', value: UptickTaxonomy },
    ]
  },
  {
    module: 'src/components/Uptick/shared/ContentMeta/ContentMeta',
    exports: [
      { name: 'ContentMeta', value: ContentMeta },
    ]
  },
  {
    module: 'next/navigation',
    exports: [
      { name: 'usePathname', value: usePathname },
      { name: 'useSearchParams', value: useSearchParams },
    ]
  },
  {
    module: 'src/components/Uptick/EditorialPageHero/EditorialPageSearch',
    exports: [
      { name: 'default', value: EditorialPageSearch },
    ]
  },
  {
    module: 'src/components/Uptick/ui/UptickCard',
    exports: [
      { name: 'Card', value: Card },
      { name: 'CardContent', value: CardContent },
    ]
  },
  {
    module: 'src/components/Uptick/TaxonomyTags/TaxonomyTags',
    exports: [
      { name: 'TaxonomyTags', value: TaxonomyTags },
    ]
  },
  {
    module: 'react-player',
    exports: [
      { name: 'default', value: ReactPlayer },
    ]
  },
  {
    module: 'src/components/Uptick/ArticleDetail/TestimonialRenderer',
    exports: [
      { name: 'TestimonialRenderer', value: TestimonialRenderer },
    ]
  },
  {
    module: 'src/components/Uptick/ArticleDetail/TextBlock',
    exports: [
      { name: 'TextBlock', value: TextBlock },
    ]
  },
  {
    module: 'src/components/Uptick/ArticleDetail/TitleBlock',
    exports: [
      { name: 'TitleBlock', value: TitleBlock },
    ]
  },
  {
    module: 'src/components/Uptick/ArticleDetail/TwoColumnQuoteBlock',
    exports: [
      { name: 'TwoColumnQuoteBlock', value: TwoColumnQuoteBlock },
    ]
  },
  {
    module: 'src/components/Uptick/ArticleDetail/TestimonialBlock',
    exports: [
      { name: 'TestimonialBlock', value: TestimonialBlock },
    ]
  },
  {
    module: 'src/components/Uptick/ArticleDetail/HorizontalLineBlock',
    exports: [
      { name: 'HorizontalLineBlock', value: HorizontalLineBlock },
    ]
  },
  {
    module: 'src/components/Uptick/ArticleDetail/AudioPlaybackBlock',
    exports: [
      { name: 'AudioPlaybackBlock', value: AudioPlaybackBlock },
    ]
  },
  {
    module: 'src/components/Uptick/ArticleDetail/ImageBlock',
    exports: [
      { name: 'ImageBlock', value: ImageBlock },
    ]
  },
  {
    module: 'src/components/Uptick/ArticleDetail/TwoColumnTextBlock',
    exports: [
      { name: 'TwoColumnTextBlock', value: TwoColumnTextBlock },
    ]
  },
  {
    module: 'src/components/Uptick/ArticleDetail/InteractiveBlock',
    exports: [
      { name: 'InteractiveBlock', value: InteractiveBlock },
    ]
  },
  {
    module: 'src/components/Uptick/ArticleDetail/VideoBlock',
    exports: [
      { name: 'VideoBlock', value: VideoBlock },
    ]
  },
  {
    module: 'react-howler',
    exports: [
      { name: 'default', value: ReactHowler },
    ]
  },
  {
    module: 'src/components/Uptick/ArticleDetail/ComponentFactory',
    exports: [
      { name: 'ComponentFactory', value: ComponentFactory },
    ]
  },
  {
    module: 'src/components/GeneralSearch/SearchResultCard',
    exports: [
      { name: 'default', value: SearchResultCard },
    ]
  },
  {
    module: 'src/components/GeneralSearch/SearchInput',
    exports: [
      { name: 'default', value: SearchInput },
    ]
  },
  {
    module: 'src/components/GeneralSearch/SearchPaginationBar',
    exports: [
      { name: 'default', value: SearchPaginationBar },
    ]
  }
] as ImportEntry[];

export default combineImportEntries(defaultImportEntries, importMap);
